spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trip
    username: root
    password: 0920
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 969542110950-o4f05po4gpihkrrjf6vpofnoi7log0og.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email

jwt:
  secretKey: 'qwjedi19hrb18odxkcnwgkjkladhnw9182nmsd0s89y12mne123mksnsaujfdhowkrn3k45786zxnmcvwjehrkeljhfjwh1'

  access:
    expiration: 300000
    header: Authorization

  refresh:
    expiration: 1200000
    header: Authorization-refresh

cloud:
  aws:
    credentials:
      access-key: AKIAU34IHXLWDLLTEAVS
      secret-key: 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
    s3:
      bucket: sunny-pj
    region:
      static: ap-southeast-2
    stack:
      auto: false