spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip_together
    username: root
    password: Tjwjdeogus369!

    jpa:
      properties:
        hibernate:
          format_sql: 'true'
      show-sql: 'true'
      hibernate:
        ddl-auto: create
        default_batch_fetch_size: 100